name: Deploy LambdaStack

on:
  push:
    branches:
      - dev

jobs:
  deploy_lambda_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: "eu-west-2"
            role-session-name: "GitHubActions-DeployLayerStack"

      - name: Deploy SwiftwadBackendStack (via CDK)
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'SwiftwadBackendStack'
          cdk_args: '--require-approval never' # This is a toy example, so we don't need to approve changes
          actions_comment: false